# This file is autogenerated by MeasureKit. DO NOT EDIT MANUALLY.

from measurement.quantity import Quantity

e: Quantity
gravitational_constant: Quantity
pi: Quantity
planck_constant: Quantity
speed_of_light: Quantity
standard_gravity: Quantity
