# This file is autogenerated by MeasureKit. DO NOT EDIT MANUALLY.

from measurement.dimensions import Dimension

ACCELERATION: Dimension
AMOUNT_OF_SUBSTANCE: Dimension
ANGLE: Dimension
AREA: Dimension
ELECTRIC_CHARGE: Dimension
ELECTRIC_CURRENT: Dimension
ENERGY: Dimension
FORCE: Dimension
FREQUENCY: Dimension
LENGTH: Dimension
LUMINOUS_INTENSITY: Dimension
MASS: Dimension
MONEY: Dimension
POWER: Dimension
PRESSURE: Dimension
TEMPERATURE: Dimension
TIME: Dimension
VELOCITY: Dimension
VOLUME: Dimension
