# ===============================================
#  Sistema de Unidades Internacional (SI)
# ===============================================

[System]
name = SI
base_units = L:m, M:kg, T:s, I:A, O:K, N:mol, J:cd, A:rad, $:USD
